### ISSUE TITLE
Subscribe is broken for multiple topics

### ISSUE THREAD

**Issue by AdamClements** [clojurewerkz/machine_head#13]
The documentation suggests it should be possible to subscribe to more than one topic with the same connection, which is sort of true, however all of the subscriptions now point to the last function meaning it's impossible to send different topics to different functions without writing custom dispatch code.

The following I would expect messages to test.one to print out "1: my message", but it actually prints "3: my message", as do messages to test.two and test.thr

```
(defn testsubs []
  (doto (mh/connect "tcp://127.0.0.1:1883" (mh/generate-id))
    (mh/subscribe ["test.one"] (fn [_ _ data] (println "1: " data)))
    (mh/subscribe ["test.two"] (fn [_ _ data] (println "2: " data)))
    (mh/subscribe ["test.thr"] (fn [_ _ data] (println "3: " data)))))
```

**Comment by jakubholynet** [comment]
@AeroNotix proposal sounds reasonable, what do you think, @michaelklishin ?

**Comment by michaelklishin** [comment]
@jakubholynet unless Paho Java API has a better option in 1.1.0, that might be OK. I'd also investigate if we could subclass Paho Java's client implementation and introduce a method that fits our needs.

Keeping handlers in a map sounds good at first but think of how it would manage accumulating subscriptions on top of Paho Java's client. That's something that can be really ugly and error prone. So it's a last resort option.

**Comment by michaelklishin** [comment]
@jakubholynet this is one of the last issues left before 1.0. I'd still prefer finding a solution that avoids double dispatch (e.g. extending Paho in Java or Clojure, I'm happy with both) if we can help it.

**Comment by jakubholynet** [comment]
No, the latest Paho doesn't provide any new solution.

Perhaps we could "fix" it by following Paho's design more closely? Namely have a separate `subscribe` and (new) `set-callback` (or we could let users pass the `on-*` functions when invoking `connect`, though that is not perfect since the client and its callback have a different lifecycle than the connection (which can be lost and re-established))? The disadvantage is that (1) it is a breaking change and (2) the user is exposed a little more to the details of how Paho works. The advantage is that it is (1) easy and (2) very unlikely to break in the future as (and if ;)) Paho evolves - contrary to subclassing it and forcing it to comply with the simpler API that we want.

So I would prefer this ☝️solution but of course can experiment with subclassing the Java client if you prefer that.

**Comment by michaelklishin** [comment]
Paho Java's API is far from being great (honestly, Paho Python is of about the same quality). It would be really unfortunate if we expose it.

So let's treat it as the last resort option.

**Comment by jakubholynet** [comment]
There actually seems to be a simple solution: using the 

```
subscribe(String[] topicFilters, int[] qos, IMqttMessageListener[] messageListeners)
```

So we would:

1. Move the `on-connection-lost, on-delivery-complete, on-connect-complete` listener from `subscribe` to `connect` and do `setCallback` there (possibly also with a `on-message`.
2. We would have `(defn subscribe [^IMqttClient client topics-and-qos handler-fn] ...)` that would not set the callback but `(.subscribe client (cnv/->topic-array topics) (cnv/->int-array qos) (into-array (repeat (count topics) (reify-message-listener handler-fn)))`

I guess this is the best option. I will give it a try.

**Comment by michaelklishin** [comment]
@jakubholynet sounds promising, thank you.

**Comment by jakubholynet** [comment]
@michaelklishin Since I will be moving `.setCallback` to `connect`, I also need to move there the various `on-` listeners. But adding a 5th parameter isn't acceptable so I propose to replace arguments 3+ with a map, i.e. go from

```clj
[^String uri ^String client-id ^MqttClientPersistence persister opts]
```
to
```clj
[^String uri ^String client-id {:keys [^MqttClientPersistence persister opts on-connection-lost on-...]}]
```
what do you think?

BTW, is the client-id argument required? Couldn't we make it optional and simply generate one ourselves if not provided? (While moving it too into the arguments map.)

**Comment by michaelklishin** [comment]
@jakubholynet 👍 . Client ID can be generated by us with a prefix and there are helper functions for that IIRC.

**Comment by jakubholynet** [comment]
@michaelklishin There is a tricky pitfall: if you use a topic with a dot, such as `mh.test1`, it will actually be changed to a slash - `mh/test1` [by RabbitMQ (MQTT plugin)](https://groups.google.com/forum/#!topic/mqtt/F5v91cVjNdA) sine Rabbit uses `.` as the separator while MQTT uses `/`. The result is that if I subscribe to "mh.test1" with my new code, I will never get any message because the actual topic checked again the subscription filter will me "mh/test1". I am not sure what to do about it. Perhaps warn the user's in `subscribe`'s docstring about this? We could also throw an exception when subscribing to a topic with a dot but I think that is too aggressive, topics with dots might work with other backends.

**Comment by michaelklishin** [comment]
@jakubholynet it will not be changed to a slash. It will be translated to AMQP 0-9-1 topic schema. MQTT clients still use slashes at all times. Only MQTT-to-AMQP 0-9-1 interop requires awareness of this translation.

**Comment by michaelklishin** [comment]
@jakubholynet I'm not trying to make this client RabbitMQ-specific. We can mention this in a doc string but it's not really a concern of every user of this client.

**Comment by jakubholynet** [comment]
Well, it took me quite a while to find out why my new subscribe code does not work :-( (since I was publishing and subscribing to "mh.test" but the message that arrived back was for "mh/test"). OK, docstring will be it then.

**Comment by michaelklishin** [comment]
@jakubholynet feel free to update our tests to something more server-neutral.
